### ISSUE TITLE
Feature request 

### ISSUE THREAD

**Issue by Cavesnakes** [prism/Prism#67] opened 2017-01-01 14:22 UTC
first, I'm so appreciate to your great work that development of Prism 1 to 3
and I'm great fan of you and your plugins 

I wish i can use Prism 2 feature like container open/close tracker or something 

already know that you busy right now, and you aren't get paid to this work

Happy new year

**Comment by viveleroi** [comment] 2017-01-01 16:13
Closing as duplicate of #11

**Closed by viveleroi** 2017-01-01 16:13 UTC
