### ISSUE TITLE
Could not pass DestructEntityEvent$Death$Impl error

### ISSUE THREAD

**Issue by Blargmode** [prism/Prism#96] opened 2017-05-08 11:55 UTC
I'm getting a lot of this error: 
```
[13:16:35] [Server thread/ERROR] [Sponge/]: Could not pass DestructEntityEvent$Death$Impl to Plugin{id=prism, name=Prism, version=3.0.0, description=A rollback/restore grief-prevention plugin., authors=[viveleroi], source=D:\Minecraft\Servers\New 2017 SpongeForge\Survival2017\mods\Prism-3.0.0-beta2-45-gfbbeb2b.jar}
org.spongepowered.api.data.DataRegistrationNotFoundException
	at org.spongepowered.common.data.SpongeManipulatorRegistry.getRegistrationFor(SpongeManipulatorRegistry.java:149) ~[SpongeManipulatorRegistry.class:1.11.2-2282-7.0.0-BETA-2305]
	at org.spongepowered.common.data.util.DataUtil.getRegistrationFor(DataUtil.java:429) ~[DataUtil.class:1.11.2-2282-7.0.0-BETA-2305]
	at org.spongepowered.common.data.util.DataUtil.getSerializedManipulatorList(DataUtil.java:132) ~[DataUtil.class:1.11.2-2282-7.0.0-BETA-2305]
	at net.minecraft.entity.Entity.toContainer(Entity.java:5804) ~[sn.class:?]
	at com.helion3.prism.api.records.PrismRecord$PrismRecordEventBuilder.writeEntity(PrismRecord.java:279) ~[PrismRecord$PrismRecordEventBuilder.class:3.0.0-beta2-45-gfbbeb2b+unknown-b0.git-unknown]
	at com.helion3.prism.api.records.PrismRecord$PrismRecordEventBuilder.killed(PrismRecord.java:239) ~[PrismRecord$PrismRecordEventBuilder.class:3.0.0-beta2-45-gfbbeb2b+unknown-b0.git-unknown]
	at com.helion3.prism.listeners.DeathListener.onDeath(DeathListener.java:34) ~[DeathListener.class:3.0.0-beta2-45-gfbbeb2b+unknown-b0.git-unknown]
	at org.spongepowered.common.event.listener.DeathListener_DeathListener_onDeath41.handle(Unknown Source) ~[?:?]
	at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.11.2-2282-7.0.0-BETA-2305]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:314) [SpongeModEventManager.class:1.11.2-2282-7.0.0-BETA-2305]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:296) [SpongeModEventManager.class:1.11.2-2282-7.0.0-BETA-2305]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:341) [SpongeModEventManager.class:1.11.2-2282-7.0.0-BETA-2305]
	at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:329) [SpongeModEventManager.class:1.11.2-2282-7.0.0-BETA-2305]
	at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:192) [SpongeImpl.class:1.11.2-2282-7.0.0-BETA-2305]
	at org.spongepowered.common.event.SpongeCommonEventFactory.callDestructEntityEventDeath(SpongeCommonEventFactory.java:511) [SpongeCommonEventFactory.class:1.11.2-2282-7.0.0-BETA-2305]
	at net.minecraft.entity.EntityLivingBase.func_70645_a(EntityLivingBase.java:3168) [sw.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70097_a(EntityLivingBase.java:3434) [sw.class:?]
	at net.minecraft.entity.passive.EntityAnimal.func_70097_a(SourceFile:62) [ww.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70030_z(EntityLivingBase.java:230) [sw.class:?]
	at net.minecraft.entity.EntityLiving.func_70030_z(EntityLiving.java:209) [sx.class:?]
	at net.minecraft.entity.Entity.func_70071_h_(Entity.java:378) [sn.class:?]
	at net.minecraft.entity.EntityLivingBase.func_70071_h_(EntityLivingBase.java:2006) [sw.class:?]
	at net.minecraft.entity.EntityLiving.func_70071_h_(EntityLiving.java:296) [sx.class:?]
	at org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:158) [TrackingUtil.class:1.11.2-2282-7.0.0-BETA-2305]
	at net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zkc000(WorldServer.java:2837) [lw.class:?]
	at net.minecraft.world.World.func_72866_a(World.java:4049) [ajs.class:?]
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840) [lw.class:?]
	at net.minecraft.world.World.func_72870_g(World.java:1932) [ajs.class:?]
	at net.minecraft.world.World.func_72939_s(World.java:6418) [ajs.class:?]
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:2174) [lw.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
```

On a SpongeForge server I set up this weekend. I don't know what to make of it.

**Comment by viveleroi** [comment] 2017-05-08 14:40
This is an error with Sponge. I've discussed it with gabizou who should have it fixed soon.

Duplicate of #92

**Closed by viveleroi** 2017-05-08 14:40 UTC
