### ISSUE TITLE
MySQL error

### ISSUE THREAD

**Issue by SnowBlitzz** [prism/Prism#43] opened 2016-07-23 15:49 UTC
This ticket was closed without a fix - reopening it: https://github.com/prism/Prism/issues/37

The details are already specified there, but for convenience purposes I'll also say it here.

1.) http://pastebin.com/ySSzcEZ3
2.) http://pastebin.com/Cwm0pkn8

These error messages only starts spamming the console when I broke a block. Just 1 single block. After a fresh restart there won't be any of these until I break or place a block. 

My MySQL settings are set up correctly, as I have other plugins connecting to the MySQL as well, and they all work fine.

**Comment by viveleroi** [comment] 2016-07-23 16:01
Which Prism version, server platform, MySQL version?

**Comment by SnowBlitzz** [comment] 2016-07-23 16:15
Prism-3.0.0-beta2-3-g07e32ca

SpongeForge 1584

The MySQL server is from the server host so I assume it should be up to date, how do I check the version?

**Comment by cartman-2000** [comment] 2016-07-30 06:11
I wonder if you could post a list of all the mods/plugins you have on the server.

**Comment by SnowBlitzz** [comment] 2016-07-30 10:22
I've tested this on a test server with just sponge, essentialcmds, pixelmon (mod) and prism.

**Comment by viveleroi** [comment] 2016-08-18 17:44
I'll have to close this until we can find steps to reproduce because I'm not seeing the issue.

**Closed by viveleroi** 2016-08-18 17:44 UTC
